import { glob } from "glob";
import path from "node:path";
import type { BotClient } from "../../client/client.js";
import type { Sound } from "./types.js";
import type { GuildMember } from "discord.js";

class SoundBoardManager {
  client: BotClient;
  constructor(client: BotClient) {
    this.client = client;
  }

  async playSound(member: GuildMember, soundId: number): Promise<string> {
    const sound = await this.getById(soundId);
    if (!sound) return "I dont have this sound.....";

    const voiceChannel = member.voice.channel;
    if (!voiceChannel) return "You are not even in voice channel....";

    const conn = await this.client.voiceManager.joinChannel(voiceChannel);
    if (!conn) return "I could not join your channel....";

    await this.client.voiceManager.playFile(voiceChannel, sound.url);
    return `<a:cd:1542916813485117470> Playing ~> ${sound.name}`;
  }

  async add(
    id: string | null,
    name: string,
    guildId: string | null,
    url: string,
  ) {
    await this.client.postgres.query(
      "insert into sounds (discord_id, name, guild_id, url) values ($1, $2, $3, $4)",
      [id, name, guildId, url],
    );
  }

  async removeDiscordSound(discordId: string) {
    await this.client.postgres.query(
      "delete from sounds where discord_id = $1",
      [discordId],
    );
  }

  async updateDiscordSound(
    discordId: string,
    name: string,
    guildId: string,
    url: string,
  ) {
    await this.client.postgres.query(
      "update sounds set name = $1, guild_id = $2, url = $3 where discord_id = $4",
      [name, guildId, url, discordId],
    );
  }

  async get(name: string): Promise<Sound | null> {
    const result = await this.client.postgres.query<Sound>(
      "select * from sounds where name = $1",
      [name],
    );
    return result.rows[0] ?? null;
  }

  async getById(id: number): Promise<Sound | null> {
    const result = await this.client.postgres.query<Sound>(
      "select * from sounds where id = $1",
      [id],
    );
    return result.rows[0] ?? null;
  }

  async all(page = 1, limit = 10): Promise<{ count: number; sounds: Sound[] }> {
    const countResult = await this.client.postgres.query<{ total: string }>(
      "select count(*) as total from sounds",
    );
    const soundsResult = await this.client.postgres.query<Sound>(
      "select * from sounds order by id limit $1 offset $2",
      [limit, (page - 1) * limit],
    );
    return {
      count: Number(countResult.rows[0]?.total ?? 0),
      sounds: soundsResult.rows,
    };
  }

  async search(
    query: string,
    page = 1,
    limit = 10,
  ): Promise<{ count: number; sounds: Sound[] }> {
    const searchTerm = `%${query}%`;
    const countResult = await this.client.postgres.query<{ total: string }>(
      "select count(*) as total from sounds where name like $1",
      [searchTerm],
    );
    const soundsResult = await this.client.postgres.query<Sound>(
      "select * from sounds where name like $1 order by id limit $2 offset $3",
      [searchTerm, limit, (page - 1) * limit],
    );
    return {
      count: Number(countResult.rows[0]?.total ?? 0),
      sounds: soundsResult.rows,
    };
  }

  async initialize() {
    await this.client.postgres.query(`
      create table if not exists sounds (
        id integer generated by default as identity primary key,
        discord_id text,
        name text not null,
        guild_id text,
        url text not null
      );
      create index if not exists idx_sounds_name on sounds(name);
    `);
    // await this.fetchFiles();
  }

  private async fetchFiles() {
    const files = await glob("files/**/*.mp3", { nodir: true });

    for (const file of files) {
      const name = path.basename(file, path.extname(file));

      await this.client.postgres.query(
        `insert into sounds (discord_id, name, guild_id, url)
         select null, $1, null, $2
         where not exists (select 1 from sounds where url = $2)`,
        [name, file],
      );
    }
  }
}

export { SoundBoardManager };
